# notify-on-fail.yml
apiVersion: v1alpha
kind: Notification
metadata:
  name: support-case-notif
spec:
  rules:
    - name: "Support Case notif"
      filter:
        projects:
          - app.options.cafe
        results:
          - failed
      notify:
        slack:
          endpoint: https://hooks.slack.com/services/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
